# Generated by Django 4.1.1 on 2022-09-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='telefone',
            field=models.CharField(max_length=16, verbose_name='Telefone'),
        ),
    ]
