# Generated by Django 4.1.1 on 2022-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_alter_contatos_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True, verbose_name='Cadastraado em:'),
        ),
    ]
