# Generated by Django 4.1.1 on 2022-09-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contatos_delete_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='data',
        ),
    ]
