# Generated by Django 4.1.1 on 2022-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_remove_contatos_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='contatos',
            name='nome',
            field=models.CharField(default=1, max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contatos',
            name='telefone',
            field=models.PositiveIntegerField(default=1, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
